import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export interface LayoutBlockPosition {
  x: number; // mm depuis la gauche de la page A4 (largeur 210mm)
  y: number; // mm depuis le haut de la page A4 (hauteur 297mm)
}

export interface LayoutBlocks {
  logo?: LayoutBlockPosition;
  company_info?: LayoutBlockPosition;
  items_table?: LayoutBlockPosition;
  totals?: LayoutBlockPosition;
  qr_code?: LayoutBlockPosition;
  signature?: LayoutBlockPosition;
}

export interface InvoiceTemplateConfig {
  theme?: string;
  primaryColor: string;   // hex, ex: "#f97316"
  secondaryColor: string; // hex
  accentColor: string;    // hex
  logoUrl?: string | null;
  fontFamily?: string;    // Arial | Roboto | Poppins | Open Sans | Inter (mappé vers une police jsPDF)
  headerLogoPosition?: "left" | "center" | "right";
  footerMentions?: string | null;
  footerConditions?: string | null;
  footerCoordonnees?: string | null;
  footerReseauxSociaux?: string | null;
  visibleColumns?: string[]; // ex: ["reference","description","quantity","unit","tva","remise","unit_price","total"]
  showSignature?: boolean;
  signatureUrl?: string | null;
  showQrCode?: boolean;
  qrCodeType?: "paiement" | "telechargement" | "verification";
  qrCodeValue?: string; // URL ou contenu à encoder, fourni par l'appelant selon qrCodeType
  watermarkEnabled?: boolean;
  language?: "fr" | "en" | "bilingue";
  currency?: string; // FCFA | XAF | USD | EUR
  useCustomLayout?: boolean;   // active le positionnement libre (glisser-déposer)
  layoutBlocks?: LayoutBlocks; // positions custom, utilisées seulement si useCustomLayout=true
}

export interface InvoicePDFItem {
  description: string;
  qty: number;
  unitPrice: number;
  reference?: string;
  unit?: string;      // ex: "pcs", "kg", "heure"
  discount?: number;  // pourcentage, ex: 10 pour 10%
  tvaRate?: number;   // taux TVA propre à la ligne, sinon tvaRate global est utilisé
}

export interface InvoicePDFData {
  code: string;
  issueDate: string;
  dueDate?: string;
  status: string; // "brouillon" | "payee" | "annulee" | "en_retard" | autre
  clientName: string;
  clientEmail?: string;
  clientPhone?: string;
  clientCity?: string;
  companyName?: string;
  companyPhone?: string;
  companyEmail?: string;
  companyAddress?: string;
  items: InvoicePDFItem[];
  notes?: string;
  tvaRate?: number;
  template?: InvoiceTemplateConfig;
}

const DEFAULT_TEMPLATE: InvoiceTemplateConfig = {
  primaryColor: "#f97316",
  secondaryColor: "#141a1a",
  accentColor: "#78827b",
  fontFamily: "Inter",
  headerLogoPosition: "left",
  visibleColumns: ["description", "quantity", "unit_price", "total"],
  language: "fr",
  currency: "FCFA",
};

const I18N = {
  fr: {
    invoice: "FACTURE", from: "DE :", to: "A :", issueDate: "Date d'emission", due: "Echeance",
    description: "Description", qty: "Qte", unit: "Unite", ref: "Ref.", tva: "TVA", discount: "Remise",
    unitPrice: "Prix unit.", total: "Total HT", subtotal: "Sous-total HT", totalTtc: "TOTAL TTC",
    notes: "Notes :", footer: "genere par FactureFlow Africa",
  },
  en: {
    invoice: "INVOICE", from: "FROM:", to: "TO:", issueDate: "Issue date", due: "Due date",
    description: "Description", qty: "Qty", unit: "Unit", ref: "Ref.", tva: "VAT", discount: "Discount",
    unitPrice: "Unit price", total: "Total", subtotal: "Subtotal", totalTtc: "TOTAL",
    notes: "Notes:", footer: "generated by FactureFlow Africa",
  },
};

const WATERMARK_LABELS: Record<string, string> = {
  brouillon: "BROUILLON", payee: "PAYEE", annulee: "ANNULEE", en_retard: "EN RETARD",
};

const FONT_MAP: Record<string, string> = {
  Arial: "helvetica", Roboto: "helvetica", Poppins: "helvetica",
  "Open Sans": "helvetica", Inter: "helvetica",
  // jsPDF n'embarque nativement que helvetica/times/courier. Pour une police custom fidèle
  // (Poppins, Inter, etc.), il faut embarquer les fichiers .ttf via doc.addFont() —
  // amélioration possible ultérieure. Pour l'instant toutes les polices retombent sur
  // Helvetica (rendu propre et universellement lisible).
};

function hexToRgb(hex: string): [number, number, number] {
  const clean = hex.replace("#", "");
  const bigint = parseInt(clean.length === 3
    ? clean.split("").map((c) => c + c).join("")
    : clean, 16);
  return [(bigint >> 16) & 255, (bigint >> 8) & 255, bigint & 255];
}

function formatCurrency(n: number, currency = "FCFA"): string {
  const formatted = Math.round(n).toString().replace(/\B(?=(\d{3})+(?!\d))/g, " ");
  if (currency === "USD") return "$" + formatted;
  if (currency === "EUR") return formatted + " €";
  return formatted + " " + currency;
}

async function loadImageAsDataUrl(url: string): Promise<string | null> {
  try {
    const res = await fetch(url);
    const blob = await res.blob();
    return await new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

async function loadQrCodeDataUrl(value: string): Promise<string | null> {
  try {
    const QRCode = (await import("qrcode")).default;
    return await QRCode.toDataURL(value, { margin: 1, width: 200 });
  } catch (err) {
    console.warn("QR code non généré (package 'qrcode' manquant ?):", err);
    return null;
  }
}

async function buildInvoiceDoc(data: InvoicePDFData): Promise<jsPDF> {
  const tpl = { ...DEFAULT_TEMPLATE, ...(data.template || {}) };
  const t = I18N[tpl.language === "en" ? "en" : "fr"];
  const cols = tpl.visibleColumns || DEFAULT_TEMPLATE.visibleColumns!;

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const W = 210;
  const fontName = FONT_MAP[tpl.fontFamily || "Inter"] || "helvetica";
  doc.setFont(fontName);

  const tvaRate = data.tvaRate ?? 0.18;
  const subtotal = data.items.reduce((s, i) => {
    const lineTotal = i.qty * i.unitPrice;
    const discounted = i.discount ? lineTotal * (1 - i.discount / 100) : lineTotal;
    return s + discounted;
  }, 0);
  const tva = Math.round(subtotal * tvaRate);
  const total = Math.round(subtotal + tva);

  const PR = hexToRgb(tpl.primaryColor);
  const SD = hexToRgb(tpl.secondaryColor);
  const AC = hexToRgb(tpl.accentColor);
  const WH: [number, number, number] = [255, 255, 255];
  const LG: [number, number, number] = [245, 247, 247];

  // Layout personnalisé (glisser-déposer) : résout la position d'un bloc,
  // avec repli sur la position par défaut si non custom ou non définie.
  const layout: LayoutBlocks = tpl.useCustomLayout ? (tpl.layoutBlocks || {}) : {};
  function blockPos(key: keyof LayoutBlocks, fallbackX: number, fallbackY: number): LayoutBlockPosition {
    return layout[key] || { x: fallbackX, y: fallbackY };
  }

  // HEADER
  doc.setFillColor(...PR);
  doc.rect(0, 0, W, 30, "F");

  const logoDataUrl = tpl.logoUrl ? await loadImageAsDataUrl(tpl.logoUrl) : null;
  const logoPos = tpl.useCustomLayout
    ? blockPos("logo", 10, 7)
    : {
        x: tpl.headerLogoPosition === "center" ? W / 2 - 8 : tpl.headerLogoPosition === "right" ? W - 26 : 10,
        y: 7,
      };
  const logoX = logoPos.x;
  const logoY = logoPos.y;
  const textX = tpl.useCustomLayout
    ? logoX + 20
    : tpl.headerLogoPosition === "center" ? W / 2 + 10 : tpl.headerLogoPosition === "right" ? W - 90 : 30;

  if (logoDataUrl) {
    doc.addImage(logoDataUrl, "PNG", logoX, logoY, 16, 16);
  } else {
    doc.setFillColor(...WH);
    doc.roundedRect(logoX, logoY, 16, 16, 2, 2, "F");
    doc.setFont(fontName, "bold");
    doc.setFontSize(11);
    doc.setTextColor(...PR);
    doc.text("F", logoX + 8, logoY + 11, { align: "center" });
  }

  doc.setTextColor(...WH);
  doc.setFontSize(12);
  doc.setFont(fontName, "bold");
  doc.text(data.companyName ?? "Mon Entreprise", textX, logoY + 7);
  doc.setFontSize(8);
  doc.setFont(fontName, "normal");
  if (data.companyAddress) doc.text(data.companyAddress, textX, logoY + 14, { maxWidth: 90 });

  // Filigrane (statut)
  if (tpl.watermarkEnabled && WATERMARK_LABELS[data.status]) {
    doc.saveGraphicsState();
    doc.setTextColor(...AC);
    doc.setFontSize(60);
    doc.setFont(fontName, "bold");
    (doc as any).setGState(new (doc as any).GState({ opacity: 0.12 }));
    doc.text(WATERMARK_LABELS[data.status], W / 2, 160, { align: "center", angle: 45 });
    doc.restoreGraphicsState();
  }

  // Titre FACTURE
  doc.setTextColor(...SD);
  doc.setFontSize(22);
  doc.setFont(fontName, "bold");
  doc.text(t.invoice, 10, 46);

  doc.setFontSize(9);
  doc.setFont(fontName, "normal");
  doc.setTextColor(...AC);
  doc.text(data.code, 10, 53);

  doc.setFontSize(8);
  doc.setTextColor(...AC);
  doc.text(t.issueDate, 130, 40);
  doc.text(t.due, 175, 40);
  doc.setFontSize(9);
  doc.setFont(fontName, "bold");
  doc.setTextColor(...SD);
  doc.text(data.issueDate, 130, 47);
  doc.text(data.dueDate ?? "-", 175, 47);

  doc.setDrawColor(...PR);
  doc.setLineWidth(0.6);
  doc.line(10, 58, 200, 58);

  // Blocs DE / A
  const companyInfoPos = blockPos("company_info", 10, 63);
  const clientInfoX = 112, clientInfoY = 63; // le bloc client reste fixe (non listé dans le cahier des charges)

  doc.setFillColor(...LG);
  doc.roundedRect(companyInfoPos.x, companyInfoPos.y, 88, 34, 2, 2, "F");
  doc.roundedRect(clientInfoX, clientInfoY, 88, 34, 2, 2, "F");

  doc.setFontSize(7);
  doc.setFont(fontName, "bold");
  doc.setTextColor(...PR);
  doc.text(t.from, companyInfoPos.x + 4, companyInfoPos.y + 8);
  doc.text(t.to, clientInfoX + 4, clientInfoY + 8);

  doc.setFontSize(9);
  doc.setFont(fontName, "bold");
  doc.setTextColor(...SD);
  doc.text(data.companyName ?? "Mon Entreprise", companyInfoPos.x + 4, companyInfoPos.y + 15);
  doc.text(data.clientName, clientInfoX + 4, clientInfoY + 15);

  doc.setFont(fontName, "normal");
  doc.setFontSize(8);
  doc.setTextColor(...AC);
  let dy = companyInfoPos.y + 21;
  if (data.companyPhone) { doc.text(data.companyPhone, companyInfoPos.x + 4, dy); dy += 5; }
  if (data.companyEmail) { doc.text(data.companyEmail, companyInfoPos.x + 4, dy); dy += 5; }
  if (data.companyAddress) doc.text(data.companyAddress, companyInfoPos.x + 4, dy, { maxWidth: 80 });

  let dy2 = clientInfoY + 21;
  if (data.clientEmail) { doc.text(data.clientEmail, clientInfoX + 4, dy2); dy2 += 5; }
  if (data.clientPhone) { doc.text(data.clientPhone, clientInfoX + 4, dy2); dy2 += 5; }
  if (data.clientCity) doc.text(data.clientCity, clientInfoX + 4, dy2, { maxWidth: 80 });

  // Colonnes dynamiques du tableau
  // "description" n'a pas de largeur fixe : elle absorbe l'espace restant (colonne flexible).
  const colDefs: Record<string, { header: string; width?: number; halign: "left" | "center" | "right" }> = {
    reference: { header: t.ref, width: 18, halign: "left" },
    description: { header: t.description, halign: "left" },
    quantity: { header: t.qty, width: 12, halign: "center" },
    unit: { header: t.unit, width: 14, halign: "center" },
    tva: { header: t.tva, width: 14, halign: "center" },
    discount: { header: t.discount, width: 16, halign: "center" },
    unit_price: { header: t.unitPrice, width: 32, halign: "right" },
    total: { header: t.total, width: 32, halign: "right" },
  };
  const activeCols = cols.filter((c) => colDefs[c]);
  const head = [activeCols.map((c) => colDefs[c].header)];
  const body = data.items.filter((i) => i.description).map((i) => {
    const lineTotal = i.qty * i.unitPrice * (i.discount ? 1 - i.discount / 100 : 1);
    return activeCols.map((c) => {
      switch (c) {
        case "reference": return i.reference || "-";
        case "description": return i.description;
        case "quantity": return String(i.qty);
        case "unit": return i.unit || "-";
        case "tva": return Math.round((i.tvaRate ?? tvaRate) * 100) + "%";
        case "discount": return i.discount ? i.discount + "%" : "-";
        case "unit_price": return formatCurrency(i.unitPrice, tpl.currency);
        case "total": return formatCurrency(lineTotal, tpl.currency);
        default: return "";
      }
    });
  });

  const itemsTablePos = blockPos("items_table", 10, 104);

  autoTable(doc, {
    startY: itemsTablePos.y,
    head, body,
    headStyles: { fillColor: PR, textColor: WH, fontStyle: "bold", fontSize: 9, halign: "center", font: fontName, cellPadding: 3 },
    bodyStyles: { fontSize: 9, textColor: SD, font: fontName, cellPadding: 3 },
    alternateRowStyles: { fillColor: LG },
    columnStyles: Object.fromEntries(activeCols.map((c, idx) => [
      idx, {
        ...(colDefs[c].width ? { cellWidth: colDefs[c].width } : { cellWidth: "auto" }),
        halign: colDefs[c].halign,
        fontStyle: c === "total" ? "bold" : "normal",
      },
    ])),
    margin: { left: itemsTablePos.x, right: 10 },
  });

  const tY = (doc as any).lastAutoTable.finalY + 6;

  const totalsPos = tpl.useCustomLayout && layout.totals
    ? layout.totals
    : { x: 120, y: tY };

  doc.setFillColor(...LG);
  doc.roundedRect(totalsPos.x, totalsPos.y, 80, 32, 2, 2, "F");

  doc.setFontSize(9);
  doc.setFont(fontName, "normal");
  doc.setTextColor(...AC);
  doc.text(t.subtotal, totalsPos.x + 4, totalsPos.y + 9);
  doc.setTextColor(...SD);
  doc.text(formatCurrency(subtotal, tpl.currency), totalsPos.x + 78, totalsPos.y + 9, { align: "right" });

  doc.setTextColor(...AC);
  doc.text(t.tva + " (" + Math.round(tvaRate * 100) + "%)", totalsPos.x + 4, totalsPos.y + 18);
  doc.setTextColor(...SD);
  doc.text(formatCurrency(tva, tpl.currency), totalsPos.x + 78, totalsPos.y + 18, { align: "right" });

  doc.setDrawColor(...PR);
  doc.setLineWidth(0.4);
  doc.line(totalsPos.x + 4, totalsPos.y + 22, totalsPos.x + 78, totalsPos.y + 22);

  doc.setFillColor(...PR);
  doc.roundedRect(totalsPos.x, totalsPos.y + 24, 80, 12, 2, 2, "F");
  doc.setTextColor(...WH);
  doc.setFontSize(10);
  doc.setFont(fontName, "bold");
  doc.text(t.totalTtc, totalsPos.x + 4, totalsPos.y + 32);
  doc.text(formatCurrency(total, tpl.currency), totalsPos.x + 78, totalsPos.y + 32, { align: "right" });

  let cursorY = tY + 42;

  if (data.notes) {
    doc.setFillColor(...LG);
    doc.roundedRect(10, cursorY, 100, 16, 2, 2, "F");
    doc.setFontSize(8);
    doc.setFont(fontName, "bold");
    doc.setTextColor(...AC);
    doc.text(t.notes, 14, cursorY + 7);
    doc.setFont(fontName, "normal");
    doc.setTextColor(...SD);
    doc.text(data.notes, 14, cursorY + 13, { maxWidth: 92 });
    cursorY += 22;
  }

  // Signature
  if (tpl.showSignature && tpl.signatureUrl) {
    const sigPos = blockPos("signature", 140, cursorY);
    const sigDataUrl = await loadImageAsDataUrl(tpl.signatureUrl);
    if (sigDataUrl) {
      doc.addImage(sigDataUrl, "PNG", sigPos.x, sigPos.y, 50, 20);
      doc.setFontSize(7);
      doc.setTextColor(...AC);
      doc.text("Signature", sigPos.x, sigPos.y + 24);
    }
  }

  // QR Code
  if (tpl.showQrCode && tpl.qrCodeValue) {
    const qrPos = blockPos("qr_code", 10, cursorY);
    const qrDataUrl = await loadQrCodeDataUrl(tpl.qrCodeValue);
    if (qrDataUrl) {
      doc.addImage(qrDataUrl, "PNG", qrPos.x, qrPos.y, 22, 22);
    }
  }

  // Pied de page
  doc.setFillColor(...PR);
  doc.rect(0, 285, W, 12, "F");
  doc.setTextColor(...WH);
  doc.setFontSize(6.5);
  doc.setFont(fontName, "normal");
  const footerLine = tpl.footerMentions || ("FactureFlow Africa - " + t.footer);
  doc.text(footerLine, 105, 290, { align: "center", maxWidth: 190 });
  if (tpl.footerCoordonnees) {
    doc.text(tpl.footerCoordonnees, 105, 294.5, { align: "center", maxWidth: 190 });
  }

  return doc;
}

export async function generateInvoicePDF(data: InvoicePDFData): Promise<void> {
  const doc = await buildInvoiceDoc(data);
  doc.save(data.code + ".pdf");
}

// Retourne une data URL (PDF encodé en base64) utilisable dans un <iframe> ou <embed>
// pour l'aperçu en temps réel dans l'éditeur de modèles, sans déclencher de téléchargement.
export async function generateInvoicePDFPreviewUrl(data: InvoicePDFData): Promise<string> {
  const doc = await buildInvoiceDoc(data);
  return doc.output("datauristring");
}